### ISSUE TITLE
Plugin keeps crashing "Error: Cannot find module 'fast-glob'"

### ISSUE THREAD

**Issue by Nusiq** [Blockception/VSCode-Bedrock-Development-Extension#15]
**Describe the bug**
Crash log:
```
[Info  - 09:06:52] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:847
    throw err;
    ^

Error: Cannot find module 'fast-glob'
Require stack:
- c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\code\ProjectData.js
- c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\database\MinecraftProgramData.js
- c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\database\Database.js
- c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\minecraft\types\Block\Completion.js
- c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\minecraft\types\include.js
- c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\minecraft\commands\CommandManager.js
- c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\manager\Extension Data.js
- c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\manager\Manager.js
- c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\server\Setup.js
- c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (c:\Users\artur\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\server\out\code\ProjectData.js:52:25)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\artur\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\\server\\out\\code\\ProjectData.js',
    'c:\\Users\\artur\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\\server\\out\\database\\MinecraftProgramData.js',
    'c:\\Users\\artur\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\\server\\out\\database\\Database.js',
    'c:\\Users\\artur\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\\server\\out\\minecraft\\types\\Block\\Completion.js',
    'c:\\Users\\artur\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\\server\\out\\minecraft\\types\\include.js',
    'c:\\Users\\artur\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\\server\\out\\minecraft\\commands\\CommandManager.js',
    'c:\\Users\\artur\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\\server\\out\\manager\\Extension Data.js',
    'c:\\Users\\artur\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\\server\\out\\manager\\Manager.js',
    'c:\\Users\\artur\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\\server\\out\\server\\Setup.js',
    'c:\\Users\\artur\\.vscode\\extensions\\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-1.0.13\\server\\out\\server.js'
  ]
}
[Error - 09:06:52] Connection to server got closed. Server will not be restarted.
```
This repeats 5 times and than VS Code decides to stop restarting the plugin.

**Screenshots**
List of installed plugins:
![obraz](https://user-images.githubusercontent.com/34062025/96413030-8b260700-11da-11eb-8822-d70ebd6d14f3.png)

**Comment by DaanV2** [comment]
I messed up a new dependencies. Fix should be there in a couple of minutes
