### ISSUE TITLE
Server Crashes when encountering a zip file.

### ISSUE THREAD

**Issue by StarkTMA** [Blockception/VSCode-Bedrock-Development-Extension#407]
The server crashes when it traverses the workspaces and encounters zip files

To reproduce just throw in a zip file inside your workspace directory.

Expected behavior
Ignores the zip file.

Error log:
`[Info  - 14:51:00] Traversing workspace: c:\Users\USERNAME\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\REDACTED\assets\vanilla\BP.zip
[Info  - 14:51:00] Traversing workspace: c:\Users\USERNAME\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds\REDACTED\assets\vanilla\RP.zip
[Info  - 14:51:00] Traversing complete
[Error - 14:51:00] message: While processing, received 2x errors
	stack:QueueError: While processing, received 2x errors
    at r.create (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:205857)
    at a.finish (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:647027)
    at a.Process (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:646379)
    at c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:646641
    at <anonymous>
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [QueueError]: While processing, received 2x errors
    at r.create (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:205857)
    at a.finish (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:647027)
    at a.Process (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:646379)
    at c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:646641
    at <anonymous> {
  errors: [
    Error: ENOTDIR: not a directory, scandir 'c:/Users/USERNAME/AppData/Local/Packages/Microsoft.MinecraftUWP_8wekyb3d8bbwe/LocalState/games/com.mojang/minecraftWorlds/REDACTED/assets/vanilla/BP.zip'
        at Object.readdirSync (node:fs:1392:3)
        at e.readdirSync (node:electron/js2c/asar_bundle:5:10830)
        at s (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1452462)
        at t.read (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1453094)
        at t.scandirSync [as _scandir] (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:420028)
        at o._handleDirectory (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1455163)
        at o._handleQueue (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1455087)
        at o.read (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1454946)
        at t.default.read (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1454633)
        at t.walkSync [as _walkSync] (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:419580) {
      errno: -4052,
      syscall: 'scandir',
      code: 'ENOTDIR',
      path: 'c:/Users/USERNAME/AppData/Local/Packages/Microsoft.MinecraftUWP_8wekyb3d8bbwe/LocalState/games/com.mojang/minecraftWorlds/REDACTED/assets/vanilla/BP.zip',
      index: 1,
      item: {
        uri: 'zip:/c%3A%5CUsers%5CUSERNAME%5CAppData%5CLocal%5CPackages%5CMicrosoft.MinecraftUWP_8wekyb3d8bbwe%5CLocalState%5Cgames%5Ccom.mojang%5CminecraftWorlds/REDACTED/assets/vanilla/BP.zip',
        name: 'BP.zip'
      }
    },
    Error: ENOTDIR: not a directory, scandir 'c:/Users/USERNAME/AppData/Local/Packages/Microsoft.MinecraftUWP_8wekyb3d8bbwe/LocalState/games/com.mojang/minecraftWorlds/REDACTED/assets/vanilla/RP.zip'
        at Object.readdirSync (node:fs:1392:3)
        at e.readdirSync (node:electron/js2c/asar_bundle:5:10830)
        at s (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1452462)
        at t.read (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1453094)
        at t.scandirSync [as _scandir] (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:420028)
        at o._handleDirectory (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1455163)
        at o._handleQueue (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1455087)
        at o.read (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1454946)
        at t.default.read (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:1454633)
        at t.walkSync [as _walkSync] (c:\Users\USERNAME\.vscode\extensions\blockceptionltd.blockceptionvscodeminecraftbedrockdevelopmentextension-4.1.22\server\out\server.js:2:419580) {
      errno: -4052,
      syscall: 'scandir',
      code: 'ENOTDIR',
      path: 'c:/Users/USERNAME/AppData/Local/Packages/Microsoft.MinecraftUWP_8wekyb3d8bbwe/LocalState/games/com.mojang/minecraftWorlds/REDACTED/assets/vanilla/RP.zip',
      index: 2,
      item: {
        uri: 'zip:/c%3A%5CUsers%5CUSERNAME%5CAppData%5CLocal%5CPackages%5CMicrosoft.MinecraftUWP_8wekyb3d8bbwe%5CLocalState%5Cgames%5Ccom.mojang%5CminecraftWorlds/REDACTED/assets/vanilla/RP.zip',
        name: 'RP.zip'
      }
    }
  ]
}
[Error - 14:51:00] The LSP-BC Minecraft server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.`

**Comment by DaanV2** [comment]
Can't seem to reproduce it, but I'm uploading a new version seeing if that helps

**Comment by DaanV2** [comment]
New version should be live, let me know if it still occruses

**Comment by StarkTMA** [comment]
No more crashes!
Thanks, that bothered me quite a lot having to reload every time it crashes.
